name: Auto Refresh Instagram Token

on:
  schedule:
    - cron: '0 0 * * 1' # كل يوم اثنين الساعة 00:00
  workflow_dispatch:     # لتشغيله يدويًا أيضًا إن أردت لاحقًا

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run token refresh script
        run: |
          python scripts/refresh_token.py
        env:
          FB_APP_ID: ${{ secrets.FB_APP_ID }}
          FB_APP_SECRET: ${{ secrets.FB_APP_SECRET }}
          FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
